Repository AY2223S2-CS2103T-T09-3/tp, pull requests merged in 2023-03, with the labels that each got.

#35 Update UserGuide for Rewards commands
  docs/UserGuide.md
Labels: documentation

#33 feat: Assign a customer as an individual or an enterprise
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CliSyntax.java
  src/main/java/seedu/loyaltylift/logic/parser/EditCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/main/java/seedu/loyaltylift/model/customer/CustomerType.java
  src/main/java/seedu/loyaltylift/model/util/SampleDataUtil.java
  src/main/java/seedu/loyaltylift/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/loyaltylift/ui/Badge.java
  src/main/java/seedu/loyaltylift/ui/CustomerCard.java
  src/main/java/seedu/loyaltylift/ui/OrderCard.java
  src/main/java/seedu/loyaltylift/ui/customer/CustomerInfo.java
  src/main/java/seedu/loyaltylift/ui/order/OrderInfo.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidCustomerAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidCustomerAddressBook.json
  src/test/data/JsonAddressBookStorageTest/missingCustomerTypeAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/logic/parser/AddCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/EditCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ParserUtilTest.java
  src/test/java/seedu/loyaltylift/model/customer/CustomerTest.java
  src/test/java/seedu/loyaltylift/model/customer/CustomerTypeTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/loyaltylift/testutil/CustomerBuilder.java
  src/test/java/seedu/loyaltylift/testutil/CustomerUtil.java
  src/test/java/seedu/loyaltylift/testutil/EditCustomerDescriptorBuilder.java
  src/test/java/seedu/loyaltylift/testutil/TypicalCustomers.java
  src/test/java/seedu/loyaltylift/ui/BadgeTest.java
Labels: type.Story

#43 feat: Add reward points to Customers
  docs/AboutUs.md
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/SetPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CliSyntax.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/logic/parser/SetPointsCommandParser.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/main/java/seedu/loyaltylift/model/customer/Points.java
  src/main/java/seedu/loyaltylift/storage/JsonAdaptedCustomer.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/SetPointsCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/SetPointsCommandParserTest.java
  src/test/java/seedu/loyaltylift/model/customer/PointsTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/loyaltylift/testutil/CustomerBuilder.java
Labels: type.Story

#36 chore: Changes to Order
  src/main/java/seedu/loyaltylift/model/order/CreatedDate.java
  src/main/java/seedu/loyaltylift/model/order/Order.java
  src/main/java/seedu/loyaltylift/model/order/Status.java
  src/main/java/seedu/loyaltylift/model/order/StatusValue.java
Labels: type.Story

#44 Add tests for Order
  src/main/java/seedu/loyaltylift/model/order/Order.java
  src/main/java/seedu/loyaltylift/model/order/Quantity.java
  src/main/java/seedu/loyaltylift/model/util/SampleDataUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/model/AddressBookTest.java
  src/test/java/seedu/loyaltylift/model/ModelManagerTest.java
  src/test/java/seedu/loyaltylift/model/order/CreatedDateTest.java
  src/test/java/seedu/loyaltylift/model/order/OrderTest.java
  src/test/java/seedu/loyaltylift/model/order/QuantityTest.java
  src/test/java/seedu/loyaltylift/model/order/StatusTest.java
  src/test/java/seedu/loyaltylift/model/order/UniqueOrderListTest.java
  src/test/java/seedu/loyaltylift/testutil/AddressBookBuilder.java
  src/test/java/seedu/loyaltylift/testutil/OrderBuilder.java
  src/test/java/seedu/loyaltylift/testutil/TypicalOrders.java
Labels: type.Chore

#61 Create Logic for Bookmarking and Un-bookmarking of customers.
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/AddPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/MarkCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/UnmarkCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/main/java/seedu/loyaltylift/model/customer/Marked.java
  src/main/java/seedu/loyaltylift/storage/JsonAdaptedCustomer.java
  src/main/resources/images/marked-icon.png
  src/main/resources/images/unmarked-icon.png
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/loyaltylift/testutil/CustomerBuilder.java
  src/test/java/seedu/loyaltylift/testutil/TypicalCustomers.java
Labels: type.Story

#69 Add command to filter orders by name
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/commons/core/Messages.java
  src/main/java/seedu/loyaltylift/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/FindOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/FindCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/loyaltylift/model/customer/CustomerNameContainsKeywordsPredicate.java
  src/main/java/seedu/loyaltylift/model/order/OrderNameContainsKeywordsPredicate.java
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/FindOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/FindCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/FindOrderCommandParserTest.java
  src/test/java/seedu/loyaltylift/model/ModelManagerTest.java
  src/test/java/seedu/loyaltylift/model/customer/CustomerNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/loyaltylift/model/order/OrderNameContainsKeywordsPredicateTest.java
Labels: type.Story

#74 Update DG and UG for notes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#71 docs: update Developer Guide with design details
  docs/DeveloperGuide.md
Labels: type.Chore

#77 Sort customer points
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CliSyntax.java
  src/main/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/Model.java
  src/main/java/seedu/loyaltylift/model/ModelManager.java
  src/main/java/seedu/loyaltylift/model/attribute/Name.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/main/java/seedu/loyaltylift/model/customer/Points.java
  src/test/java/seedu/loyaltylift/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ParserUtilTest.java
Labels: type.Story

#73 Created Bookmark UI
  build.gradle
  src/main/java/seedu/loyaltylift/ui/Bookmark.java
  src/main/java/seedu/loyaltylift/ui/CustomerCard.java
  src/main/resources/view/Bookmark.fxml
  src/test/java/seedu/loyaltylift/ui/BookmarkTest.java
Labels: type.Story

#86 Filter Orders by Status
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ListOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CliSyntax.java
  src/main/java/seedu/loyaltylift/logic/parser/ListOrderCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/order/OrderNameContainsKeywordsPredicate.java
  src/main/java/seedu/loyaltylift/model/order/OrderStatusPredicate.java
  src/test/java/seedu/loyaltylift/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ListOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ListOrderCommandParserTest.java
  src/test/java/seedu/loyaltylift/model/order/OrderStatusPredicateTest.java
Labels: type.Story

#95 feat: add UI for Points
  src/main/java/seedu/loyaltylift/ui/Badge.java
  src/main/java/seedu/loyaltylift/ui/CustomerCard.java
  src/main/java/seedu/loyaltylift/ui/customer/CustomerGeneralInfo.java
  src/main/resources/images/points.png
  src/main/resources/view/Customer/CustomerGeneralInfo.fxml
  src/main/resources/view/CustomerListCard.fxml
Labels: type.Story

#88 Edited ListCustomerCommand to allow for filter option.
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/test/java/seedu/loyaltylift/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParserTest.java
Labels: type.Story

#92 feat; add viewo command
  src/main/java/seedu/loyaltylift/logic/commands/CommandResult.java
  src/main/java/seedu/loyaltylift/logic/commands/ExitCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/HelpCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ViewCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ViewOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ViewOrderCommandParser.java
  src/main/java/seedu/loyaltylift/ui/CustomerListPanel.java
  src/main/java/seedu/loyaltylift/ui/MainWindow.java
  src/main/java/seedu/loyaltylift/ui/OrderListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/loyaltylift/logic/commands/CommandResultTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ExitCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/HelpCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ViewCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ViewOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ViewOrderCommandParserTest.java
Labels: type.Enhancement

#97 Filter customers by customer type
  docs/UserGuide.md
  src/main/java/seedu/loyaltylift/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ListOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/ListOrderCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/customer/CustomerTypePredicate.java
  src/test/java/seedu/loyaltylift/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ListCustomerCommandParserTest.java
Labels: type.Story

#98 fix: Set FXML JavaFX version to 11
  src/main/resources/view/Badge.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/Customer/CustomerGeneralInfo.fxml
  src/main/resources/view/Customer/CustomerInfo.fxml
  src/main/resources/view/Customer/CustomerOrderCard.fxml
  src/main/resources/view/Customer/CustomerOrderListPanel.fxml
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/Order/OrderGeneralInfo.fxml
  src/main/resources/view/Order/OrderHistoryPanel.fxml
  src/main/resources/view/Order/OrderInfo.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug

#89 As a user, I can advance, revert, and cancel an order
  src/main/java/seedu/loyaltylift/logic/commands/AdvanceOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/CancelOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/RevertOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddressBookParser.java
  src/main/java/seedu/loyaltylift/logic/parser/AdvanceOrderStatusCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CancelOrderCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/RevertOrderStatusCommandParser.java
  src/main/java/seedu/loyaltylift/model/AddressBook.java
  src/main/java/seedu/loyaltylift/model/order/Order.java
  src/main/java/seedu/loyaltylift/model/order/Status.java
Labels: type.Story

#103 feat: view tier of customers based on their cumulative points
  src/main/java/seedu/loyaltylift/model/customer/Points.java
  src/main/java/seedu/loyaltylift/ui/Badge.java
  src/main/java/seedu/loyaltylift/ui/customer/CustomerGeneralInfo.java
  src/main/resources/images/tier.png
  src/main/resources/view/Customer/CustomerGeneralInfo.fxml
Labels: type.Story

#106 docs: Update UG for PE dryrun, no settier command
  docs/UserGuide.md
Labels: type.Chore

#105 Update user guide
  docs/UserGuide.md
  docs/images/advanceOrderResult.png
  docs/images/cancelOrderResult.png
  src/main/java/seedu/loyaltylift/logic/commands/FindOrderCommand.java
Labels: type.Chore
