Repository AY2223S2-CS2103T-T09-3/tp, pull requests merged in 2023-04, with the labels that each got.

#153 Multiple fixes made
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/loyaltylift/storage/JsonSerializableAddressBookTest.java
Labels: type.Bug

#161 chore: Update User Guide Command Formats
  docs/UserGuide.md
  docs/assets/css/style.scss
Labels: type.Chore

#162 fix: Fix case-sensitive Name sorting
  src/main/java/seedu/loyaltylift/model/attribute/Name.java
Labels: type.Bug

#163 fix: Prevent notes from overflowing
  src/main/resources/view/NotePanel.fxml
Labels: type.Bug

#165 chore: Update test cases
  src/test/java/seedu/loyaltylift/logic/parser/AddPointsCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AppendCustomerNoteCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AppendOrderNoteCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/SetCustomerNoteCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/SetOrderNoteCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/SetPointsCommandParserTest.java
Labels: type.Chore

#164 chore: Change message for invalid index
  src/main/java/seedu/loyaltylift/commons/core/Messages.java
  src/main/java/seedu/loyaltylift/logic/commands/AddOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AddPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AdvanceOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AppendCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AppendOrderNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/CancelOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/RevertOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetOrderNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ViewCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/ViewOrderCommand.java
  src/test/java/seedu/loyaltylift/logic/LogicManagerTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AppendCustomerNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AppendOrderNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/EditCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/SetCustomerNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/SetOrderNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ViewCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/ViewOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddPointsCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/SetPointsCommandParserTest.java
Labels: type.Chore

#168 chore: Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Chore

#172 chore: Change caution in UG as cancelled orders can be reverted
  docs/UserGuide.md
Labels: type.Chore

#159 chore: Remove display of last updated and last ordered in UI cards
  src/main/resources/view/Customer/CustomerOrderCard.fxml
  src/main/resources/view/CustomerListCard.fxml
Labels: type.Chore

#160 chore: Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MarkCustomerSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/MarkCustomerSequenceDiagram.png
Labels: type.Chore

#166 Throw exception functionality added
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
Labels: type.Chore

#171 fix: Fix bugs related to commands
  src/main/java/seedu/loyaltylift/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AddOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AddPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AdvanceOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AppendCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AppendOrderNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/CancelOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/FindOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/RevertOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetOrderNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/model/ModelManager.java
  src/test/java/seedu/loyaltylift/logic/commands/AddCustomerCommandIntegrationTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AppendCustomerNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AppendOrderNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/EditCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/FindOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/SetCustomerNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/SetOrderNoteCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
Labels: type.Bug

#173 docs: Final update for UG
  docs/UserGuide.md
  docs/images/addingFirstCustomerResult.png
  docs/images/addingPointsResult.png
  docs/images/helpMessage.png
  docs/images/markcResult.png
  docs/images/setPointsResult.png
  docs/images/setpointsExampleResult.png
  docs/images/subtractingPointsResult.png
  docs/images/unmarkcResult.png
  docs/images/viewoBananaCakeResult.png
Labels: type.Bug, type.Chore

#174 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Chore

#176 chore: Change save files to loyaltylift
  src/main/java/seedu/loyaltylift/commons/core/LogsCenter.java
  src/main/java/seedu/loyaltylift/model/UserPrefs.java
  src/main/java/seedu/loyaltylift/storage/JsonSerializableAddressBook.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/loyaltylift/storage/JsonUserPrefsStorageTest.java
Labels: type.Chore

#181 chore: Add customers manual testing to DG
  docs/DeveloperGuide.md
Labels: type.Chore

#180 Update User Guide
  docs/UserGuide.md
  docs/images/FreshUi.png
  docs/images/Ui.png
  docs/images/addingFirstCustomerOrderClearResult.png
  docs/images/addingFirstCustomerOrderResult.png
  docs/images/addingFirstCustomerResult.png
  docs/images/addingPointsResult.png
  docs/images/advanceOrderResult.png
  docs/images/advoBananaCakeResult.png
  docs/images/cancelOrderResult.png
  docs/images/cliFailure.png
  docs/images/cliSuccess.png
  docs/images/findAlexDavidResult.png
  docs/images/loyaltyLiftLayout.png
  docs/images/markcBerniceYuResult.png
  docs/images/setPointsResult.png
  docs/images/setnotecBetsyResult.png
  docs/images/subtractingPointsResult.png
  docs/images/viewcBerniceYuResult.png
  docs/images/viewoBananaCakeResult.png
Labels: type.Chore

#182 Update DG model component
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Chore

#191 fix: Fix portfolio links in project website
  docs/AboutUs.md
Labels: type.Chore

#179 Edited DeveloperGuide, PPP
  docs/DeveloperGuide.md
  docs/team/javonteo.md
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
Labels: type.Chore

#183 chore: Update PPP for CloudHill
  docs/team/cloudhill.md
Labels: type.Chore

#186 test: Touch up and add final test cases for 1.4
  src/test/java/seedu/loyaltylift/logic/parser/ParserUtilTest.java
  src/test/java/seedu/loyaltylift/model/customer/CustomerTest.java
  src/test/java/seedu/loyaltylift/model/customer/PointsTest.java
  src/test/java/seedu/loyaltylift/ui/BadgeTest.java
Labels: type.Chore

#184 docs: Update DG architecture section
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/plantuml/ArchitectureSequenceDiagram.png
Labels: type.Chore

#192 Update PPP javonteo.md
  docs/team/javonteo.md
Labels: type.Chore

#167 Remove Tag class and references
  src/main/java/seedu/loyaltylift/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AddPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AppendCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/MarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetCustomerNoteCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/SetPointsCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/CliSyntax.java
  src/main/java/seedu/loyaltylift/logic/parser/EditCustomerCommandParser.java
  src/main/java/seedu/loyaltylift/logic/parser/ParserUtil.java
  src/main/java/seedu/loyaltylift/model/customer/Customer.java
  src/main/java/seedu/loyaltylift/model/tag/Tag.java
  src/main/java/seedu/loyaltylift/model/util/SampleDataUtil.java
  src/main/java/seedu/loyaltylift/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/loyaltylift/storage/JsonAdaptedTag.java
  src/test/java/seedu/loyaltylift/logic/LogicManagerTest.java
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/EditCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/loyaltylift/logic/commands/MarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/UnmarkCustomerCommandTest.java
  src/test/java/seedu/loyaltylift/logic/parser/AddCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/EditCustomerCommandParserTest.java
  src/test/java/seedu/loyaltylift/logic/parser/ParserUtilTest.java
  src/test/java/seedu/loyaltylift/model/AddressBookTest.java
  src/test/java/seedu/loyaltylift/model/customer/CustomerTest.java
  src/test/java/seedu/loyaltylift/model/customer/UniqueCustomerListTest.java
  src/test/java/seedu/loyaltylift/model/tag/TagTest.java
  src/test/java/seedu/loyaltylift/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/loyaltylift/testutil/CustomerBuilder.java
  src/test/java/seedu/loyaltylift/testutil/CustomerUtil.java
  src/test/java/seedu/loyaltylift/testutil/EditCustomerDescriptorBuilder.java
  src/test/java/seedu/loyaltylift/testutil/TypicalCustomers.java
Labels: type.Bug

#195 fix: developer guide architecture sequence diagram in wrong folder
  docs/diagrams/plantuml/ArchitectureSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Chore

#199 docs: fix visual bug in UG
  docs/UserGuide.md
Labels: type.Chore

#193 chore: Update PPP for Junyi00
  docs/team/junyi00.md
Labels: type.Chore

#196 chore: Update Developer Guide And DevOps.md
  docs/DevOps.md
  docs/DeveloperGuide.md
Labels: type.Chore

#194 docs: update PPP
  docs/team/infrix.md
Labels: type.Chore

#203 Update Developer Guide
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/MarkCustomerSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/MarkCustomerSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: type.Chore

#200 Create order tests
  src/main/java/seedu/loyaltylift/commons/core/Messages.java
  src/main/java/seedu/loyaltylift/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AddOrderCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/AdvanceOrderStatusCommand.java
  src/main/java/seedu/loyaltylift/logic/commands/EditOrderCommand.java
  src/main/java/seedu/loyaltylift/model/util/SampleDataUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AddOrderDescriptorTest.java
  src/test/java/seedu/loyaltylift/logic/commands/AdvanceOrderStatusCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/CancelOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/CommandTestUtil.java
  src/test/java/seedu/loyaltylift/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/EditOrderCommandTest.java
  src/test/java/seedu/loyaltylift/logic/commands/RevertOrderStatusCommandTest.java
  src/test/java/seedu/loyaltylift/testutil/AddOrderDescriptorBuilder.java
  src/test/java/seedu/loyaltylift/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/loyaltylift/testutil/OrderBuilder.java
Labels: type.Chore

#205 chore: Update CloudHill PPP
  docs/team/cloudhill.md
Labels: type.Chore

#206 chore: Update jednghk PPP
  docs/team/jednghk.md
  src/main/java/seedu/loyaltylift/logic/commands/EditCustomerCommand.java
Labels: type.Chore

#209 Fixed Infrix.md link error
  docs/team/infrix.md
Labels: type.Bug

#214 chore: Fix minor errors in UG
  docs/UserGuide.md
  docs/images/cliFailure.png
Labels: type.Chore
